### ISSUE TITLE
AssertionError: data parallel group is not initialized

### ISSUE THREAD

**Issue by victorup** [THUDM/SwissArmyTransformer#82]
Hi, 
I encounter an error as follows: 

Traceback (most recent call last):
  File "/data33/private/xinpeng/codebase/CogView2/pretrain_coglm.py", line 244, in <module>
    training_main(args, model_cls=BaseModel, forward_step_function=forward_step, create_dataset_function=create_dataset_function)
  File "/home/xinpeng/miniconda3/envs/cogview/lib/python3.9/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 66, in training_main
    train_data, val_data, test_data = make_loaders(args, hooks['create_dataset_function'])
  File "/home/xinpeng/miniconda3/envs/cogview/lib/python3.9/site-packages/SwissArmyTransformer/data_utils/configure_data.py", line 166, in make_loaders
    group=mpu.get_data_parallel_group())
  File "/home/xinpeng/miniconda3/envs/cogview/lib/python3.9/site-packages/SwissArmyTransformer/mpu/initialize.py", line 97, in get_data_parallel_group
    assert _DATA_PARALLEL_GROUP is not None, \
AssertionError: data parallel group is not initialized

**Comment by victorup** [comment]
Thank you for your reply. This issue is a little complex. I have installed SwissArmyTransformer version SwissArmyTransformer==0.2.12 and attempted to fine-tune Cogview2 using deepspeed. The process I followed is shown in the following image:

![image](https://user-images.githubusercontent.com/44796817/233418486-dce57d21-6d77-4fce-b106-598e0d60e2a6.png)

Could you please help me resolve these issues? And please let me know if there are any errors in my commands. Thanks!

**Comment by Sleepychord** [comment]
I think you should downgrade your deepspeed（it's 0.6.x in my memory）to and use the original code. I will add support for new deepspeed version soon发自我的手机-------- 原始邮件 --------发件人： Xinpeng Wang ***@***.***>日期： 2023年4月20日周四 半夜11:51收件人： THUDM/SwissArmyTransformer ***@***.***>抄送： Sleepy_chord ***@***.***>, Comment ***@***.***>主    题： Re: [THUDM/SwissArmyTransformer] AssertionError: data parallel group is not initialized (Issue #82)
Thank you for your reply. This issue is a little complex. I have installed SwissArmyTransformer version SwissArmyTransformer==0.2.12 and attempted to fine-tune Cogview2 using deepspeed. The process I followed is shown in the following image:

Could you please help me resolve these issues? And please let me know if there are any errors in my commands. Thanks!

**Comment by victorup** [comment]
When I downgraded deepspeed to version 0.6.3, it worked. Thank you!
